excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://tranc99.github.io
title: Code Au Zeyron
email: tmutunhire@gmail.com
author: Tendai Mutunhire
description: My thoughts on technology, entrepreneurship and the future of code.
paginate: 3
google_analytics:
